# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Check for service folder existsence
  ansible.builtin.stat:
    path: "{{ omnia_service_dir }}"
  register: service_folder_status

- name: Create service folder if it doesn't exists
  ansible.builtin.file:
    path: "{{ omnia_service_dir }}"
    state: directory
    mode: "{{ mount_dir_perm }}"
  when: not service_folder_status.stat.exists

- name: Copy the shell script to /home directory
  ansible.builtin.template:
    src: "{{ omnia_service_shell_template }}"
    dest: "{{ omnia_service_shell_file_path }}"
    mode: "{{ shell_file_permissions }}"

- name: Copy the systemd service file
  ansible.builtin.template:
    src: "{{ omnia_service_template }}"
    dest: "{{ omnia_service_path }}"
    mode: "{{ service_file_permissions }}"

- name: Enable omnia service
  ansible.builtin.service:
    name: omnia.service
    enabled: true

- name: Start omnia service
  ansible.builtin.service:
    name: omnia.service
    state: started
